// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updaterecord12112016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updaterecord12112016));
        
        string IMigrationMetadata.Id
        {
            get { return "201611121149355_updaterecord-12112016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
