// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatePosition0811201601 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatePosition0811201601));
        
        string IMigrationMetadata.Id
        {
            get { return "201611080942024_updatePosition08112016-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
