// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetradereview2110201613 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetradereview2110201613));
        
        string IMigrationMetadata.Id
        {
            get { return "201610231155371_update trade review21102016-13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
