// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTradeOrder101020162 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTradeOrder101020162));
        
        string IMigrationMetadata.Id
        {
            get { return "201610100945073_updateTradeOrder10102016-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
