// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateRecord0711201603 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateRecord0711201603));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071043181_updateRecord07112016-03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
