// <auto-generated />
namespace Screen2.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeqsxeod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeqsxeod));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051142150_remove-qsxeod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
